### ISSUE TITLE
what is the proper response when favicon.ico is not present?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [CrowdHailer/raxx_static#1]
What is the proper response to give when favicon.ico is not present?

Ideally it should be a 404, or a default icon of some sort.

Presently Raxx_static just falls through and returns the default route content - which is a full page, not an icon.

your thoughts?

**Comment by CrowdHailer** [comment]
Should an icon be returned for `/favicon.ico` on a JSON api. Also I think that the default route content has status 404

**Comment by CharlesOkwuagwu** [comment]
> Should an icon be returned for /favicon.ico on a JSON api?

For branding ... maybe

**Comment by CrowdHailer** [comment]
I don't think anything needs doing on this. `favicon.ico` is a special path for browser apps but not all applications.
