### ISSUE TITLE
Emmm... Seems that we should not ban :POST method

### ISSUE THREAD

**Issue by SchrodingerZhu** [CrowdHailer/raxx_static#4]
I ran into a big trouble after upgrading to `0.8.0`. This can only handle `:GET` method, but seems that when I post a request from a page managed by a module with layout to a API module without layout, it will crash!

**Comment by SchrodingerZhu** [comment]
I suggest that we'd better not transfer  `:POST` into Raxx.Static's stack.

**Comment by CrowdHailer** [comment]
Can you add your code as an example

**Comment by SchrodingerZhu** [comment]
My last comment is not correct. It seems that we do need to process post request in my situation. Codes will be post later.

**Comment by SchrodingerZhu** [comment]
[my project](https://github.com/schrodingerzhu/personal). See " \<address\>/auth"(in `auth.ex`). This page will post a request to build a session to " \<address\>/auth/handshake"(in `user_auth.ex`)

**Comment by CrowdHailer** [comment]
@SchrodingerZhu #5 should fix this. Can you confirm it does

**Comment by CrowdHailer** [comment]
Fix released https://hex.pm/packages/raxx_static/0.8.1
